// Generated by Wrangler by running `wrangler types -e development`

interface Env {
	KV: KVNamespace;
	ENV: "dev";
	PUBLIC_BUCKET_URL: "https://r2.puddleshine.bristlefrost.net";
	DISCORD_APPLICATION_ID: "1208788796821340281";
	BUCKET: R2Bucket;
	PUBLIC_BUCKET: R2Bucket;
	DB: D1Database;
	ASSETS: Fetcher;
}
